### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by Yuji-Shimohira-Calvo** [kylebarron/stata-exec#19]
Hello! I've been trying to get stata-exec work but I always hit the same error:

```
2018-01-13 23:47:57,358 ERROR - service - Script error
Traceback (most recent call last):
  File "/home/ysc/.local/lib/python3.6/site-packages/autokey-0.94.0-py3.6.egg/autokey/service.py", line 460, in execute
    exec(script.code, scope)
  File "<string>", line 8, in <module>
  File "/home/ysc/.local/lib/python3.6/site-packages/autokey-0.94.0-py3.6.egg/autokey/scripting.py", line 848, in wait_for_focus
    if regex.match(self.mediator.interface.get_window_title()):
TypeError: cannot use a string pattern on a bytes-like object
```

I'm not 100% sure if this belongs here or if it's an issue with AutoKey, but I was hoping you could throw some light on this error (I'm happy to investigate further from there). Please feel free to close this thread if this actually isn't a problem of stata-exec. Thanks a lot!

**Comment by kylebarron** [comment]
That's really weird, and definitely looks like an autokey issue. I'll look into it on Tuesday

**Comment by kylebarron** [comment]
What Linux distro are you running? Do you know if you're running GTK or QT?

And can you try this: From the status bar, click the Autokey icon and choose "Display Window Info". 
![image](https://user-images.githubusercontent.com/15164633/35000991-cb780d62-fab3-11e7-959e-67ad63c4d21b.png)
Then if you click a window, for example the AutoKey window, it'll come up with the window properties. 
![image](https://user-images.githubusercontent.com/15164633/35001033-e5ed37d0-fab3-11e7-916c-e793afc2f120.png)

Based on that error, I'm guessing that this won't work for you.

**Comment by Yuji-Shimohira-Calvo** [comment]
Hi, thanks for looking into this!

I'm on Fedora 27, running GTK. For some reason AutoKey doesn't show in my system tray (other software does), so now I'm 100% convinced that there's a problem with my AutoKey installation. I'll see if it shows up after installing it again---I wouldn't like to waste your time if this isn't your app's issue :)

**Comment by kylebarron** [comment]
Have you started the autokey program? If you've installed autokey, the `autokey-gtk` binary should be in your path. Type `autokey-gtk` from your command line and see if an "A" shows up in your system tray.

**Comment by Yuji-Shimohira-Calvo** [comment]
Yes, AutoKey was installed via pip and runs (apparently) fine except for the fact that doesn't show up in my system tray (and doesn't work with stata-exec). If I do `autokey-gtk` the process (supposedly) runs but without icon in my systray. When I do `autokey-gtk -c` I can see perfectly fine the interface (which made me think that it was properly installed). The error I reported comes from running it in verbose: `autokey-gtk -l` and trying to send a command from Atom to Stata.

**Comment by kylebarron** [comment]
Do any of the default scripts work for you? For example, try mapping a hotkey to the "Insert Date" snippet and see if that works. Beyond that I think you'll need to post an issue in the autokey repo...
![image](https://user-images.githubusercontent.com/15164633/35013492-9b50d876-fadb-11e7-870a-62c4b81ba5e0.png)

**Comment by kylebarron** [comment]
Before you post an issue on the autokey repo, can you try a modified version of `linux/stata-exec.py`:
```py
# Enter script code
import time
from os.path import expanduser, join
shortdelay = 0.2
current = window.get_active_title()

window.activate("Stata/")

cmd = open(join(expanduser('~'), '.stata-exec_code'),'r').read()

time.sleep(shortdelay)
keyboard.send_keys(cmd)
keyboard.send_keys("<enter>")

time.sleep(shortdelay)
window.activate(current)
```

From your traceback it seems like autokey is having issues with the `wait_for_focus()` function I use [here](https://github.com/kylebarron/stata-exec/blob/master/linux/stata-exec.py#L8). That isn't strictly necessary; I think it just means that it does nothing if it can't find the Stata window.

**Comment by Yuji-Shimohira-Calvo** [comment]
Thanks a lot for your efforts, but I am now convinced it is a problem with my AutoKey installation. Running AutoKey in verbose I get an error when trying to map hotkeys (there's no object to map anything to, it complains). That would explain why stata-exec doesn't work.

I'll try to get my AutoKey installation sorted out. Thanks again for taking the time to look into this!

PS: please feel free to close this thread :)

**Comment by kylebarron** [comment]
Sounds good. There's already an issue in their repo for this thread: https://github.com/autokey/autokey/issues/66.

**Comment by kylebarron** [comment]
I updated the script from the suggestion in issue #20; try again and see if it works.
