### ISSUE TITLE
Linux Support (Arch Linux)

### ISSUE THREAD

**Issue by AndrewCSQ** [kylebarron/stata-exec#20]
Hi I'm trying to get this package working on an Arch Linux instance.

I've installed autokey (and ensured that there is an autokey-gtk instance running) and linked the stata-exec.py file as per the instructions on the package readme.

But whenever I attempt to run any code (full do file or line by line) I get an error from Autokey with the following output:

Script name: 'stata-exec'
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/autokey/service.py", line 460 in execute
exec(script.code, scope)
File "<string>", line 8, in <module>
File "/usr/lib/python3.6/site-packages/autokey/scripting.py", line 848, in wait_for_focus
if regex.match(self.mediator.interface.get_window_title()):
TypeError: cannot use a string pattern on a bytes-like object

For reference, I've tried with both xstata and a terminal instance of stata

**Comment by kylebarron** [comment]
This seems to be the same issue that @Yuji-Shimohira-Calvo was having in #19. Can you try replacing `linux/stata-exec.py` with the following text?

```
import time
from os.path import expanduser, join
shortdelay = 0.2
current = window.get_active_title()

window.activate("Stata/")

cmd = open(join(expanduser('~'), '.stata-exec_code'),'r').read()

time.sleep(shortdelay)
keyboard.send_keys(cmd)
keyboard.send_keys("<enter>")

time.sleep(shortdelay)
window.activate(current)
```

What version of autokey are you running? For me, it looks like I'm running `0.93.10-1` and is working fine.

**Comment by ppoppitz** [comment]
I got the same error with version 1.3.1 and autokey 0.94.0 on arch linux and can confirm that the alternative script works.

**Comment by kylebarron** [comment]
The script that didn't work on Arch Linux was helpful on Ubuntu because it would only paste code if it found the Stata window. I added a try-except clause that should keep the beneficial part for Ubuntu and pass over it when it gets the `TypeError` as above. Try updating to the newest version and let me know if it works.
