### ISSUE TITLE
shift-cmd-G used for search backwards

### ISSUE THREAD

**Issue by andreamoro-git** [kylebarron/stata-exec#21]
Hi, shift-cmd-G is basically used by all software for finding a string backwards. I know it's configurable but I don't think a package should hijack commonly used shortcuts.

**Comment by kylebarron** [comment]
There are so many standard keybindings that ship with Atom that it's horribly difficult to define six commands that don't interfere with what anyone else might want. Just disable the package's standard keybindings
![image](https://user-images.githubusercontent.com/15164633/35691917-d1fe9bf6-0747-11e8-937e-52f1b112d12b.png)

and put this in your `keymap.cson`:
```cson
'.platform-darwin atom-text-editor[data-grammar="source stata"]:not([mini])':
  'shift-cmd-C': 'stata-exec:set-working-directory'
  'cmd-enter': 'stata-exec:send-command'
  'shift-cmd-D': 'stata-exec:do-entire-file'
  'shift-cmd-R': 'stata-exec:send-program'
  #'shift-cmd-newletter': 'stata-exec:send-paragraph'
  'alt-shift-P': 'stata-exec:send-previous-command'
```

And you're done.

**Comment by kylebarron** [comment]
It's also not "universal" because it's not <kbd>ctrl</kbd>-<kbd>shift</kbd>-<kbd>G</kbd> on Linux; it's <kbd>shift</kbd>-<kbd>F3</kbd>
![image](https://user-images.githubusercontent.com/15164633/35692908-904291e2-074a-11e8-9f9f-0881fca7ec02.png)
