### ISSUE TITLE
Uncaught Error: CreateInstance: stata.StataOLEApp Invalid class string

### ISSUE THREAD

**Issue by stevencollinscn** [kylebarron/stata-exec#24]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [stata-exec](https://github.com/kylebarron/stata-exec) package 1.4.2

### Stack Trace

Uncaught Error: CreateInstance: stata.StataOLEApp Invalid class string

```
At C:\Users\liqia\.atom\packages\stata-exec\node_modules\winax\activex.js:4

Error: CreateInstance: stata.StataOLEApp Invalid class string

    at /packages/stata-exec/node_modules/winax/activex.js:4:12)
    at Object.sendCode (/packages/stata-exec/lib/stata-exec.js:204:22)
    at Object.sendCommand (/packages/stata-exec/lib/stata-exec.js:147:10)
    at HTMLElement.subscriptions.add.atom.commands.add (/packages/stata-exec/lib/stata-exec.js:92:45)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.24.1/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.24.1/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:19.9.0 intentions:highlight (input.hidden-input)
     -0:19.6.0 stata-exec:send-command (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.6 
atom-runner 2.7.1 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
copy-on-select 0.2.0 
file-icons 2.1.17 
highlight-selected 0.13.1 
intentions 1.1.5 
language-stata 1.3.1 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
material 2.2.0 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
python-autopep8 0.1.3 
script 3.17.3 
stata-exec 1.4.2 
Visual-Studio-2015-Dark-Theme 2.4.2 
visual-studio-code 0.4.0 
visual-studio-dark-syntax 0.2.0 
```

**Comment by kylebarron** [comment]
> Hi Kyle! It's working now! However, for some reasons, it is unable to read files. Once you open the dataset via Stata's menu, except the "use" command, everything works great! It won't be a problem if you are just working on one dataset, but it will be a huge issue if you need to open datasets and merge them together based on your need. 
>
> The problem was indeed about registering Stata. The Stata support hasn't contacted me back, so I tried myself. 
> 1. I tried to register it in cmd but it didn't work. 
> 2. Then I went to stata's folder (under c:/Program Files (x86)/Stata15), and then I right-clicked the stata exe file (named as Stata-64) to create a shortcut. 
> 3. Then the following message appears: 
"Windows can't create a shortcut here. Do you want the shortcut to be placed on the desktop instead? "
> 4. I clicked "Yes". Then I right-click the "Stata-64-Shortcut" on the desktop and choose "Properties". In the "Target" field, I add " /Register" (no " ") after the initial text or path. I was here last night, but my mistake was that I didn't realize there is a space before "/Register". And then I clicked "Apply" and "OK". After that, I right-click it again and choose "run as administrator". After that, I restarted Atom, and use "ctrl+enter" to send command and stata opened. It runs! 
I drag the shortcut on the desktop back to Stata's folder since I don't wanna see it there. It is still working. I later deleted it and it is still working.
>
> I tried to post it on Github but realized that you have deleted the instruction for wins.
>
> btw, I'm using Windows 10  Stata/IC 15  Atom 1.24.1

@stevencollinscn Check the path again. Are you in the right current directory? I wouldn't be surprised if it opened in a weird current directory.

The instructions for Windows are still on the readme. If you're referring to the issue with my notes, that's closed but still exists and you can still comment on it: https://github.com/kylebarron/stata-exec/issues/4.

By the way [Hydrogen](https://atom.io/packages/hydrogen) is a more full featured way of running Python from atom than python-runner.

**Comment by stevencollinscn** [comment]
@kylebarron By directory, if you mean whether i put the .do file and .dta file under the same folder, then I'm sure that both at the same place and there's also nothing wrong with the spelling of .dta file name. I write the do file with stata's own text editor and ran it many times before.

**Comment by kylebarron** [comment]
No; I mean see what the result of `pwd` is after you open Stata. It's not necessarily obvious to me that this way of opening stata would open Stata in the current directory of the file you're running it from.

**Comment by kylebarron** [comment]
I just tried this out in my VM and I was correct; it starts Stata for me with the directory `C:\Windows\system32`.
![image](https://user-images.githubusercontent.com/15164633/37468926-7e8b80ba-283a-11e8-983b-2bc93901631a.png)

**Comment by stevencollinscn** [comment]
Hi, Kyle. I just updated and unfortunately, it is no longer working. I
already posted it on Github.
