### ISSUE TITLE
Doesn't break for input

### ISSUE THREAD

**Issue by jcspilio** [kylebarron/stata-exec#25]
Hi Kyle!

When running a piece of Stata code which includes a prompt, such as `display "Question" _request(answer)`, Stata won't break as it usually does to allow the user to input the "answer." I can't seem to find a way around it—other than not using such prompts... 

Is that something that can be fixed, or should I just come to terms with this **absolutely tragic** flaw of your otherwise awesome package? ;)

Thanks,
Jesse

**Comment by kylebarron** [comment]
I didn't even know Stata had the possibility of doing that. 

This package is designed for interactive work, so it sends each command individually instead of as a do file. There really isn't much I can do to work around that. I'd say just don't run those lines interactively

**Comment by jcspilio** [comment]
Thanks for the heads-up. All the best!
