### ISSUE TITLE
Uncaught ReferenceError: ActiveXObject is not defined

### ISSUE THREAD

**Issue by stevencollinscn** [kylebarron/stata-exec#26]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [stata-exec](https://github.com/kylebarron/stata-exec) package 1.4.3

### Stack Trace

Uncaught ReferenceError: ActiveXObject is not defined

```
At C:\Users\liqia\.atom\packages\stata-exec\lib\stata-exec.js:205

ReferenceError: ActiveXObject is not defined
    at Object.sendCode (/packages/stata-exec/lib/stata-exec.js:205:26)
    at Object.sendCommand (/packages/stata-exec/lib/stata-exec.js:147:10)
    at HTMLElement.subscriptions.add.atom.commands.add (/packages/stata-exec/lib/stata-exec.js:92:45)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.24.1/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.24.1/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:07.4.0 intentions:highlight (input.hidden-input)
     -0:07.2.0 stata-exec:send-command (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.6 
atom-runner 2.7.1 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
copy-on-select 0.2.0 
file-icons 2.1.17 
highlight-selected 0.13.1 
Hydrogen 2.3.0 
intentions 1.1.5 
language-stata 1.3.1 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
material 2.2.0 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
python-autopep8 0.1.3 
script 3.17.3 
stata-exec 1.4.3 
Visual-Studio-2015-Dark-Theme 2.4.2 
visual-studio-code 0.4.0 
visual-studio-dark-syntax 0.2.0 
```

**Comment by kylebarron** [comment]
I think this means that when you update the package, you have to do step 4 of the Windows installation again

**Comment by stevencollinscn** [comment]
@kylebarron reinstalled it and it is working now!!!!!!! I'm truly grateful for your work! One later question, is it possible to add to the shortcut of the command that sending codes from atom to stata into the right-click menu so that I don't have to press keyboard after selecting the codes. I'm looking for a right-click menu customization package but didn't find any.

**Comment by stevencollinscn** [comment]
I just tried intentionally to leave no empty line after the last line of my codes in the do file and then send the whole do file to stata and it works. Do you forget to delete this in your note?

**Comment by kylebarron** [comment]
Making right click menus is a not insignificant amount of work and I'm not going to do that.

On Mac I think I sometimes send the file as a do file instead of interactively; that needs the empty last line.

**Comment by stevencollinscn** [comment]
I understand. It would be nice to run the code after selecting it right away. anyway. 
I'm right-hand; it is not convenient for me to use "ctrl+enter" to send command. 
Is there any way to edit this shortcut to sometimes, like "ctrl+shift" or something?

**Comment by kylebarron** [comment]
the command is named `stata-exec:send-command` not `editor:...`

**Comment by stevencollinscn** [comment]
Thank you @kylebarron. It is working now. It is funny that I still encounter those issues I posted on Github sometimes, like just now, after editing the shortcut, but it is back to normal once I restart Atom. 
I will definitely recommend your package to my friends; most of them won't even know cmd. 
I wish you are working on making the Wins installation easily.
Once again, thank you for this amazing work.
