### ISSUE TITLE
Instruction to register Stata from Stata support

### ISSUE THREAD

**Issue by stevencollinscn** [kylebarron/stata-exec#29]
> If your Windows login has restricted permissions you may need to register Stata
> using the method outlined for Vista:
> In the installation directory, right-click on the Stata executable, for example, Stata-64.exe. Choose "Create Shortcut".
> 1. Right click on the newly created "Shortcut to Stata-64.exe", Choose "Property", and change the Target from "C:\Program Files\Stata15\Stata-64.exe" to 
"C:\Program Files\Stata15\Stata-64.exe" /Register. Click "OK".
> 2. Right-click on the updated "Shortcut to Stata-64.exe"; choose "Run as administrator".
> Note: Windows Automation is case sensitive so if you forget to capitalize one letter it will not register the Stata executable correctly.

**Comment by kylebarron** [comment]
yeah that's the same as their support page I link to in the readme
https://www.stata.com/automation/#install
