### ISSUE TITLE
Allow batch mode processing of dofiles

### ISSUE THREAD

**Issue by bbdaniels** [kylebarron/stata-exec#30]
All code appears to run in the open Stata window, unlike in the [scripts](https://www.statalist.org/forums/forum/general-stata-discussion/general/516978-atom-text-editor-with-stata) implementation. It would be great to have the option to run code in batch mode so that it can be run while working interactively with other data.

**Comment by kylebarron** [comment]
What platform are you using?

**Comment by bbdaniels** [comment]
macOS High Sierra v10.13.4

As a configuration note: on scripts there is the need to edit $PATH to do this properly since the name and location of the file can vary depending on the Stata install. So this is likely not something that can be setup completely automatically. For example mine is /Applications/Stata/StataSE.app/Contents/MacOS/ which contains stata, stata-se, and StataSE. Thank you!

**Comment by kylebarron** [comment]
Is there a benefit of adding this support within stata-exec over using stata-exec for anything interactive and the scripts package for full do files?

**Comment by bbdaniels** [comment]
Perhaps not! I am currently testing out the muscle memory for using shift-cmd-d for interactive runs and cmd-i for batch runs and it is so far so good. But since stata-exec is the advertised method of running stata scripts on your [language-stata](https://atom.io/packages/language-stata) page I thought it could be useful to wrap that all into this one place since Stata tends to require more specialized fussing with than other packages run in script.

**Comment by kylebarron** [comment]
Well who doesn't like to advertise their own programs? :smile: 

I might get around to this next week. Would you want there to be a log file created? I'm not sure I'd be able to suppress it. I would have to run entire do files at a time in the background

**Comment by bbdaniels** [comment]
Haha no it's great work! 👍🏼 

Log files are probably a good default and the Stata shell command doesn't have a nolog option IIRC, but it should be easy enough to determine where it will be placed and delete it if that's desired?

**Comment by kylebarron** [comment]
Somehow I'd forgotten, the `Run All` command uses batch mode, i.e. `do file.do`. I just haven't implemented saving a selection as a tempfile.

**Comment by bbdaniels** [comment]
This would be very helpful if it is not terribly difficult since the current implementation can result in unexpected behavior by macros such as counters.

**Comment by kylebarron** [comment]
Fixed in latest release. https://github.com/kylebarron/stata-exec/commit/7f6aa5e4108ec62e85457d9fe532ea6cc1b849c9
