### ISSUE TITLE
Package building failed

### ISSUE THREAD

**Issue by SumaiyaR** [kylebarron/stata-exec#33]
I tried to work with stata-exec and followed the steps exactly. But I got this in the end:

npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs winax
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls winax
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sumai\.atom\packages\stata-exec\npm-debug.log

**Comment by toniopap** [comment]
I have the same problem...

**Comment by kylebarron** [comment]
As mentioned in the README:

> This package can potentially work on Windows but is very hard to get right, so it's not officially supported. I would strongly recommend Windows users try [`stata_kernel`](https://kylebarron.dev/stata_kernel/) which has a much easier installation process on Windows.
