### ISSUE TITLE
VS Code

### ISSUE THREAD

**Issue by ahnafalrafi** [kylebarron/stata-exec#39]
Would it be possible to make this available for Visual Studio Code, similar to language-stata? I am contemplating moving my work to VS Code because it is faster, but I love the functionality offered by stat-exec.

Thanks!

**Comment by kylebarron** [comment]
As far as I know, VSCode uses a completely different API, so I'd have to completely rewrite the package. I only use Atom so that's not something I want to do. 

You're welcome to fork this and try to make the VSCode package

**Comment by kylebarron** [comment]
I'm closing this because I have no plans to make a VSCode package.
