### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata-exec#4]
The key part of StataEditor is [here](https://github.com/mattiasnordin/StataEditor/blob/a37d9e529e2082b2d1f76f1a6c045d2e2a69dc22/StataEditorPlugin.py#L60).

```python
import Pywin32.setup
import win32com.client
import win32api
...
def StataAutomate(stata_command):
	""" Launch Stata (if needed) and send commands """
	try:
		sublime.stata.DoCommandAsync(stata_command)

	except:
		win32api.WinExec(settings.get("stata_path"))
		sublime.stata = win32com.client.Dispatch("stata.StataOLEApp")
		sublime.stata.DoCommand("cd " + getDirectory())
		sublime.stata.DoCommandAsync(stata_command)
```

**Comment by kylebarron** [comment]
## Possible solution 1:
The StataEditor package uses the above python packages to create a COM connection to Stata. Instead of reinventing the wheel, try to call that python package from Javascript. [Make an ajax request to python](https://stackoverflow.com/questions/13175510/call-python-function-from-javascript-code):
```js
$.ajax({
  type: "POST",
  url: "~/pythoncode.py",
  data: { param: text}
}).done(function( o ) {
   // do something
});
```
Note that I think this uses the jQuery package. Here are links to use that with Coffeescript:
[Coffeescript Cookbook jQuery and Ajax](https://coffeescript-cookbook.github.io/chapters/jquery/ajax)
[jQuery with CoffeeScript](https://css-tricks.com/jquery-coffeescript/)

Other javascript-ajax-python links: [1](https://stackoverflow.com/questions/32288722/call-python-function-from-js), [2](https://stackoverflow.com/questions/15151133/execute-a-python-script-on-button-click).

## Possible solution 2:
Do this directly from javascript/coffeescript. 

[Calling a VBScript function from Javascript](https://stackoverflow.com/questions/466059/calling-vbscript-from-javascript-or-vice-versa)
[How can i call VBscript from Javascript](https://stackoverflow.com/questions/17995847/how-can-i-call-vbscript-from-javascript)
[SO example VBScript](https://stackoverflow.com/questions/16441179/vbscript-for-automated-website-login-testing)
[What does win32com.client.Dispatch() do?](https://stackoverflow.com/questions/23500274/what-exactly-does-win32com-client-dispatchwscript-shell)
[Quick Start to Client side COM and Python](http://docs.activestate.com/activepython/3.3/pywin32/html/com/win32com/HTML/QuickStartClientCom.html)

## General References
[Stata Automation Reference](https://www.stata.com/automation/)
[OLE Automation in JavaScript](http://www.webreference.com/js/column55/index.html)
- Info on:
```
What Automation is
What binding is
How to create a new instance of an Automation object
How to retrieve an existing instance of an Automation object
How to work with application instances
How to improve the performance of your scripts
How to work with collection objects
```

[OLE Automation Wikipedia](https://en.wikipedia.org/wiki/OLE_Automation)
[Component Object Model (COM)](https://en.wikipedia.org/wiki/Component_Object_Model)



Note that Javascript is not necessarily the same as JScript.

**Comment by mcaceresb** [comment]
The python code is storing `stata.StataOLEApp`, and that is why you get a persistent session. The thing to do would be to create a "stata" object in atom in javascript. Not sure whether that is possible, but I don't think you can get a persistent session using python. As best I can tell, it works for sublime because "sublime' is an object in python which can store "stata".

Perhaps this: https://www.npmjs.com/package/win32com? You'd need to rewrite the snippet in js/cson, but the syntax looks pretty similar.

**Comment by kylebarron** [comment]
Yeah, I see that `stata.StataOLEApp`. I've been in the midst of working to install the node module as we speak. The github repo hasn't been updated in 5 years so it might not work. I'll see

**Comment by mcaceresb** [comment]
Fingers crossed. FWIW, the hash repo I used for gtools hasn't been updated in 3 years and it works just fine, but I understand it feels a bit like rolling the dice. Best of luck!

**Comment by kylebarron** [comment]
Thanks!!! I got it to work. 

To document my progress:
- Had to install [node-activex](https://github.com/durs/node-activex). This is what creates the connection. Ideally, you should be able to do just `npm install winax`, but that didn't exactly work on my computer. 
![image](https://user-images.githubusercontent.com/15164633/33299662-a3399d86-d3ba-11e7-838c-ceaf65bfd5ed.png)

- I had to fidget with my environment variables...
    - I have a `%PYTHON%` variable at `C:\Program File\Python36`
![image](https://user-images.githubusercontent.com/15164633/33299407-75172dac-d3b9-11e7-84c7-b5a8dd69cd52.png)

    - My `%PATH%` looks like: 
![image](https://user-images.githubusercontent.com/15164633/33299389-590495d2-d3b9-11e7-9cb3-bef8253d7081.png)

- I also did
    ```bash
    npm --add-python-to-path='true' --debug install --global windows-build-tools
    ```
    this had to be done in an administrative level command prompt. See [this issue](https://github.com/felixrieseberg/windows-build-tools/issues/56).


Once everything is correctly installed, the following worked:
```node
var winax = require('winax');
var con = new ActiveXObject("stata.StataOLEApp", {
    activate: true,
    async: true,
    type: true
});
con.DoCommandAsync('sysuse auto, clear');
```
![image](https://user-images.githubusercontent.com/15164633/33299245-bafa0110-d3b8-11e7-9e1c-c2af7b423707.png)

### To do:
- Figure out how to get this to install with the fewest number of manual dependencies.
- Do they need to install python?
- Get this working inside Atom.

**Comment by kylebarron** [comment]
Still trying to get it to work in Atom. It works in the node console, but not in Atom's dev console. Not sure why it can't find the module.

![image](https://user-images.githubusercontent.com/15164633/33300336-bd4046a0-d3bd-11e7-9eb5-f5740c853b3b.png)

**Comment by kylebarron** [comment]
Possibly helpful: https://electronjs.org/docs/tutorial/using-native-node-modules

I need to read more about electron

**Comment by kylebarron** [comment]
Likely impossible to have this work from Atom. Atom is built on Electron, which is built on Chrome, and Chrome doesn't support ActiveX. 

See:
- https://github.com/durs/node-activex/issues/15
- https://stackoverflow.com/questions/36309779/invoke-activex-in-electron#36314844

**Comment by kylebarron** [comment]
You can still do batch mode:
```
"C:\Program Files (x86)\Stata15\StataMP-64.exe" /e do test.do
```
Probably the only possibility

**Comment by kylebarron** [comment]
https://atom.io/packages/ide-bash

```
npm install -g bash-language-server
```
> You need to install that language server separately as it depends on native node modules

look into this and see if there's something like this I could do for Stata

**Comment by kylebarron** [comment]
- [native node modules](https://electronjs.org/docs/tutorial/using-native-node-modules)
- [node-gyp windows](https://github.com/nodejs/node-gyp#option-1)
- [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools)

**Comment by kylebarron** [comment]
It works!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

From an admin-level command prompt, install `windows-build-tools`
```
npm install --global --production windows-build-tools
```

Then rebuild winax against the current electron version. Get the current electron version with
```
process.versions.electron
```

Then rebuild with:
```
npm rebuild winax --runtime=electron --target=1.6.15 --disturl=https://atom.io/download/atom-shell --build-from-source
```

**Comment by kylebarron** [comment]
![image](https://user-images.githubusercontent.com/15164633/37219018-34fefd9a-2390-11e8-9b0f-cfd07e72e9d6.png)

**Comment by kylebarron** [comment]
Fixed with https://github.com/kylebarron/stata-exec/commit/1059ae8982438726f37a86af2287c7e2c536ddb4
