### ISSUE TITLE
The results are not shown in the Atom, but instead are shown in the StataSE

### ISSUE THREAD

**Issue by Kailasa** [kylebarron/stata-exec#48]
Thanks for this awesome package! It's super cool!

I am using mac and I encountered a minor issue. The screenshots on this page (https://kylebarron.dev/stata_kernel/#screenshots) show that you can get the results in the atom console right after you run some commands. But on my mac, I can't get the results displayed in Atom. Instead, it jumps back to the Stata and show me the results in Stata every time I run a command in Atom. Do you know how to fix this?

**Comment by kylebarron** [comment]
`stata_kernel` and `stata-exec` are two different things. To use `stata_kernel`, uninstall or disable `stata-exec`
