### ISSUE TITLE
Send entire command strung together with ///

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata-exec#5]
Send entire command with `send-command` without needing to select everything in the below instance:
```stata
di 2 + ///
    2
```
Look and see if the current line (or last line of the selection) matches a regex for `/// [a-z]* (?=\n)`. If so, include the next line in the selection, and do this recursively.

**Comment by acarril** [comment]
This would be great. As a matter of fact, even when selecting everything everything in a block of code like the one you mention above, it still doesn't run it correctly with `send-command`. I've attached a screenshot.
![screenshot from 2018-01-08 18-14-18](https://user-images.githubusercontent.com/9773292/34697169-ea391148-f49f-11e7-9ddd-258867f13890.png)

**Comment by kylebarron** [comment]
That's weird because it does work for me

![image](https://user-images.githubusercontent.com/15164633/34730267-e19911fe-f52c-11e7-9751-42c36533df7c.png)

**Comment by guanghwang** [comment]
I have the same issue on linux.

**Comment by kylebarron** [comment]
My issue was that I had solved this issue in November after pushing 1.2.1, and then got busy and forgot that I hadn't pushed the newest version to Atom. I this realized last Friday and didn't have an opportunity to update the package till now. 

tl,dr: Update the package and it should work.

**Comment by guanghwang** [comment]
It works now. Thanks
